tower:
  trustedEmails:
    - '*@hack.com'
---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
  security:
    session:
      enabled: false
    token:
      jwt:
        enabled: true
        bearer:
          enabled: true
        signatures:
          secret:
            generator:
              secret: this_secret_has_32_characters...
        generator:
          accessTokenExpiration: 3600
---
dataSource:
  pooled: false
  dbCreate: create
  url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ""
hibernate:
  show_sql: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: org.hibernate.dialect.H2Dialect
  naming_strategy: io.seqera.util.H8NamingStrategy
grails:
  gorm:
    failOnError: false
---
mail:
  debug: true
  from: me@google.com
  smtp:
    host: localhost
    port: 3025
    user: mr-bean
    password: super-secret
    auth: true
    starttls:
      enable: false
      required: false
    proxy:
      host: proxy.com
      port: 5566
---
auth:
  mail:
    duration: 30m
---
<<<<<<< HEAD
live:
  buffer:
    time: 1500ms
    count: 10
    heartbeat: 5s
