tower:
  trustedEmails:
    - '*@hack.com'
---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
---
dataSource:
  pooled: false
  dbCreate: create
  url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ""
hibernate:
  show_sql: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: org.hibernate.dialect.H2Dialect
  naming_strategy: io.seqera.util.H8NamingStrategy
grails:
  gorm:
    failOnError: false
---
mail:
  debug: true
  from: me@google.com
  smtp:
    host: localhost
    port: 3025
    user: mr-bean
    password: super-secret
    auth: true
    starttls:
      enable: false
      required: false
    proxy:
      host: proxy.com
      port: 5566
---
auth:
  mail:
    duration: 30m
---
sse:
  time:
    idle:
      workflow: 1m
      user: 1m
    throttle:
      workflow: 0s
      user: 0s
    heartbeat:
      user: 1m
