---
dataSource:
  pooled: true
  dbCreate: create
  url: jdbc:mysql://localhost:3307/tower
  driverClassName: com.mysql.cj.jdbc.Driver
  username: tower
  password: tower
hibernate:
  show_sql: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: io.seqera.util.MySQL55DialectCollateBin
  naming_strategy: io.seqera.util.H8NamingStrategy
grails:
  gorm:
    failOnError: false
---
mail:
  debug: true
  from: me@google.com
  smtp:
    host: localhost
    port: 3025
    user: mr-bean
    password: super-secret
    auth: true
    starttls:
      enable: false
      required: false
    proxy:
      host: proxy.com
      port: 5566
---
auth:
  mail:
    duration: 30m
